apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: morshed983/morshed983:${BUILD_NUMBER}
        env:
        - name: REDIS_HOST
          value: localhost
        ports:
        - containerPort: 8000
      - name: redius 
        image: redis
        ports:  
        - containerPort: 6379
